### ISSUE TITLE
Missing 1 required keyword-only argument: 'intents'

### ISSUE THREAD

**Issue by spmedia** [ail-project/ail-feeder-discord#26]
When attempting to run ail-feeder-discord from source and monitor:

Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\GitHub\ail-feeder-discord\bin\feeder.py", line 69, in <module>
    discordlib.monitor(download=download)
  File "C:\Users\xxxx\Documents\GitHub\ail-feeder-discord\bin\discordlib.py", line 633, in monitor
    client = DiscordMonitor()
             ^^^^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

Looks like Intents are required now for Discord

https://discordpy.readthedocs.io/en/stable/migrating.html#intents-are-now-required

**Comment by spmedia** [comment]
ping @adulau @Terrtia  :)

**Comment by Terrtia** [comment]
Hi @spmedia !

It seem to work with the latest version of https://github.com/dolfies/discord.py-self (discord.py-self in the requirement)
Is the issue still occurring?

**Comment by spmedia** [comment]
That was my issue! Thank you for the response!
